site_name: RingSeqPy
site_url: https://example.com/
theme:
  name: "material"
plugins:
  - mkdocstrings
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: index.md
  - What is a circular sequence: what-is.md
  - Usage examples: usage.md
  - Reference: reference.md
  - RingSeq methods: ring_seq_methods.md
  - GitHub repository: github.md
