site_name: RingSeqPy
site_url: https://example.com/
site_description: RingSeqPy library documentation.
site_author: Mario Càllisto

repo_url: https://github.com/scala-tessella/ring-seq-py/

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github

plugins:
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - What is a circular sequence: what-is.md
  - Usage examples: usage.md
  - Reference: reference.md
  - RingSeq methods: ring_seq_methods.md

copyright: Copyright &copy; 2024 Mario Càllisto.